<?php
    require 'controlador_agenda.php';
    session_start();
    if (!isset($_SESSION['usuario_online']) or !$_SESSION['usuario_online'] == true){
        header('Location: login.php');
    }
    if (isset($_GET['nome_buscado'])){
        $meusContatos = buscar($_GET['nome_buscado']);
    } else {
        $meusContatos = pegar_contatos();
    }

?>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Agenda</title>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body id="body">

	
	<div class="container" style="margin-top: 30px;" >

		<h3>MINHA AGENDA DE CONTATOS</h3>
		<br />
		
		<!-- CADASTRO-->
		<div class="row">
			<div class="col-md-12">
				<form class="form-inline" method="post" action="controlador_agenda.php?acao=cadastrar">
				  
				  <!--nome-->
				  <div class="form-group">
				    <label for="nome">Nome</label>
				    <input name="nome" type="text" class="form-control" id="nome">
				  </div>
				  
				  <!--email-->
				  <div class="form-group">
				    <label for="email">Email</label>
				    <input name="email" type="email" class="form-control" id="email">
				  </div>

				  <!--telefone-->
				  <div class="form-group">
				    <label for="telefone">Telefone</label>
				    <input name="telefone" type="number" class="form-control" id="telefone">
				  </div>
				  
				  <button type="submit" class="btn btn-default">CADASTRAR</button>
				
				</form>
			</div>
		</div>

		<br />
        <form class="form-horizontal" method="get" action="">
            <fieldset>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="textinput">Busca</label>
                    <div class="col-md-4">
                        <input id="textinput" name="nome_buscado" type="text" placeholder="digite sua busca" class="form-control input-md">
                    </div>
                </div>

                <!-- Button -->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="singlebutton">Busque</label>
                    <div class="col-md-4">
                        <button id="singlebutton" name="" class="btn btn-warning">Buscar</button>
                    </div>
                </div>

            </fieldset>
        </form>

        <br>

        <!--CONTATOS-->
		<div class="row">
			<div class="col-md-12">

				<!-- Conteúdo -->
				<table class="table"> 
					<thead> 
						<tr> 
							<th>#</th> 
							<th>Nome</th> 
							<th>Email</th> 
							<th>Telefone</th> 
							<th>acoes</th>
						</tr>
					</thead> 
					<tbody> 
						<!-- repetir -->
                        <?php foreach ($meusContatos as $contato): ?>
						<tr> 
							<th scope="row"><?= $contato['id'] ?></th>
							<td><?= $contato['nome'] ?></td>
							<td><?= $contato['email'] ?></td>
							<td><?= $contato['telefone'] ?></td>
							<td><a href="editar.phtml?id=<?= $contato['id'] ?>">editar</a> | <a href="controlador_agenda.php?acao=excluir&id=<?= $contato['id'] ?>">excluir</a></td>
						</tr>
                    <?php  endforeach; ?>
					</tbody> 
				</table>
			</div>
		</div>
	</div>
</body>
</html>
